services:
  python:
    container_name: app
    image: python:latest
    build: 
      context: ./app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000
    volumes: 
      - ./app:/app
    depends_on:
      - neo4j
    networks: 
      - net

  neo4j:
    container_name: notes_project_neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/5(I07)UTZzU
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins
    networks:
      - net

networks:
  net:
    driver: bridge